apiVersion: v1
kind: Service
metadata:
  name: bench-api
  labels:
    app: bench-api
spec:
  clusterIP: None
  selector:
    app: bench-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bench-api
  labels:
    app: bench-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bench-api
  template:
    metadata:
      labels:
        app: bench-api
    spec:
      containers:
      - name: bench-api
        image: bench-api
